### ISSUE TITLE
release before publishing the blog post

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/pint-xarray#166]
With `pint=0.19` out we can hopefully publish the blog post very soon (I mean, I guess I said that a few months ago as well, but this time it's hopefully true). There are a few issues we should try to fix first:
- [x] #164
- [x] ~#151~ most likely rejected
- [x] ~#144~ (postponed to a later release) 
- [x] ~#136~ (this is a bug in `pint`)
- [x] #47 / #175
- [x] #2 would also be good to have, but I guess that's a bit more work?

**Comment by TomNicholas** [comment]
I think there is another problem: compatibility with pint's `master` branch. 

I tried updating my PRs to use the `master` version of pint just now and I'm getting import errors saying that `from pint.quantity import Quantity` won't work because pint appears to have made internal changes that mean there is no longer a module named `quantity`. (Perhaps I should make a new issue for this?)

**Comment by keewis** [comment]
it seems like #177 slightly broke the index page, I'll try to figure out why that happened and release afterwards

**Comment by keewis** [comment]
I've just published the release :tada: It should be on PyPI by now, and will soon be on `conda-forge` once that picks it up.
