### ISSUE TITLE
release 0.1

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/pint-xarray#25]
Remaining tasks for the release:
- [x] docs (#20)
- [x] testing functions (#24)
- [x] inline reprs (#20)
- [ ] ~`sel` / `loc`~
- [x] remove placeholder functions (`plus_minus`, `to_base_units`, `to_system`) (#29)
- [x] fix the properties (#31)
- [x] rework and document the global registry mechanism (#7, #26, #32)

(feel free to add to this list)

**Comment by keewis** [comment]
gentle ping, @jthielen. Any updates on this?

**Comment by jthielen** [comment]
@keewis So sorry for the delay! These past couple weeks really got out of hand for me. I hope to take care of this `sel`/`loc` port as well as addressing the requested reviews later this week.

**Comment by keewis** [comment]
sure, I just wanted to make sure this was not forgotten.

**Comment by keewis** [comment]
@jthielen, what do you think about releasing after merging #31 and #32? I think it should be fine to include `sel` / `loc` in 0.2.

**Comment by dcherian** [comment]
:+10000:

There's lots of value in releasing and letting people try it out.

**Comment by keewis** [comment]
`pint-xarray` is on PyPI :tada:

**Comment by dcherian** [comment]
Someone should tweet this out and the xarray handle can then retweet it.

**Comment by keewis** [comment]
:+1:, although I can't do that myself since I don't use twitter
