### ISSUE TITLE
unit-aware versions of unsupported functions

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/pint-xarray#70]
See also #6.

Due to a variety of reasons, [some functions](https://xarray.pydata.org/en/latest/duckarrays.html#missing-features) don't support units (partially or not at all). Since that seems unlikely to change in the near future, we can provide wrapper functions that handle the units before passing them to the appropriate `xarray` function.

I'm currently planning to add these:
- [x] `sel` (#60)
- [x] `drop_sel` (#73)
- [x] `loc` (#79)
- [x] `reindex` / `reindex_like` (#69)
- [x] `interp` / `interp_like` (#72)
- [x] `ffill` / `bfill` (#78)
- [x] `chunk` (to convert wrapped `numpy` to `dask`) (#83)
- [x] `interpolate_na` (#82)

**Comment by keewis** [comment]
I will hold off on `interpolate_na` because it might be possible to replace the call to `numpy.vectorize` by broadcasting correctly (which, considering that `vectorize` is essentially a python loop, might also be faster).

**Comment by keewis** [comment]
after discussion it seems that supporting `interpolate_na` is difficult right now: `numpy.interp` does not support the `axis` kwarg (which is the reason for `vectorize`) and `scipy` does not support duckarrays

**Comment by keewis** [comment]
as for `chunk`: is chunking after `quantify` something we should support? `rechunk` does work properly, but `da.from_array` will use `pint.Quantity` as `meta`.
