### ISSUE TITLE
release v0.2

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/pint-xarray#80]
Now that most of the wrapper methods are implemented, it might be good to release soon.

Must have:
- [x] #70: unit-aware wrapper methods
- [x] #42, #43, #92: more context in error messages
- [ ] #2: more introductory examples / a gallery

Nice to have:
- [ ] #47
- [x] #89: expose `setup_registry`
- [ ] #91: get `matplotlib.units` to work with `xarray`'s `plot` accessor

Feel free to edit this message if you feel something is missing.

cc @jthielen, @TomNicholas

**Comment by keewis** [comment]
with #92 being close (I'm going to merge it this weekend), all that's left is to increase the number of tutorials. Does anyone have ideas for that?

**Comment by keewis** [comment]
@jthielen, @TomNicholas, I probably won't be able to come up with an idea for a tutorial. Does anyone have any ideas? If not, should we go ahead with the release?

**Comment by keewis** [comment]
the mail is sent :tada:
